services:
  blackstar_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackstar_bot_container

    working_dir: /app

    command: uv run main.py

    env_file:
      - .env

    restart: unless-stopped
